SELECT Apellidos FROM empleados;
SELECT DISTINCT Apellidos FROM empleados;
SELECT * FROM empleados WHERE Apellidos = 'Smith';
SELECT * FROM empleados WHERE Apellidos = 'Smith' OR Apellidos = 'Rogers';
SELECT * FROM empleados WHERE Departamento = 14;
SELECT * FROM empleados WHERE Departamento IN (37,77);
SELECT * FROM empleados WHERE Apellidos LIKE 'P%';
SELECT SUM(Presupuesto) FROM departamentos;
SELECT Departamento, COUNT(*) FROM empleados GROUP BY Departamento;
SELECT * FROM empleados, departamentos WHERE empleados.Departamento = departamentos.Codigo;
SELECT e.Nombre, Apellidos, d.Nombre, Presupuesto FROM empleados e, departamentos d WHERE e.Departamento = d.Codigo;
SELECT e.Nombre, Apellidos FROM empleados e, departamentos d WHERE e.Departamento = d.Codigo AND d.Presupuesto > 60000;
SELECT * FROM departamentos WHERE Presupuesto > (SELECT AVG(Presupuesto) FROM departamentos);

INSERT INTO departamentos VALUES ( 11 , 'Calidad' , 40000); INSERT INTO empleados VALUES ('89267109', 'Esther', 'Vázquez', 11);
UPDATE departamentos SET Presupuesto = Presupuesto * 0.9;
UPDATE empleados SET Departamento = 14 WHERE Departamento = 77;
DELETE FROM empleados WHERE Departamento = 14;
DELETE FROM empleados WHERE Departamento IN (SELECT Codigo FROM departamentos WHERE Presupuesto > 60000);
DELETE FROM empleados;