SELECT * FROM almacenes;
SELECT * FROM cajas WHERE Valor > 150;
SELECT DISTINCT Contenido FROM cajas;
SELECT AVG(Valor) FROM cajas;
SELECT Almacen, AVG(Valor) FROM cajas GROUP BY Almacen;
SELECT Almacen, AVG(Valor) FROM cajas GROUP BY Almacen HAVING AVG(Valor) > 150;
SELECT NumReferencia, Lugar FROM almacenes, cajas WHERE almacenes.Codigo = cajas.Almacen;
SELECT Almacen, COUNT(*) FROM cajas GROUP BY Almacen;
SELECT Codigo FROM almacenes WHERE Capacidad < (SELECT COUNT(*) FROM cajas WHERE Almacen = Codigo);
SELECT NumReferencia FROM cajas WHERE Almacen IN (SELECT Codigo FROM almacenes WHERE Lugar = 'Bilbao');
INSERT INTO almacenes(codigo, Lugar, Capacidad) VALUE(6, 'Barcelona', 3);
INSERT INTO cajas VALUE('H5RT', 'Papel', 200, 2);
UPDATE cajas SET Valor = Valor * 0.85;
UPDATE cajas SET valor = valor * 0.80 WHERE valor > (SELECT AVG(cajas2.valor) FROM (SELECT * FROM cajas) cajas2);
DELETE FROM cajas WHERE Valor < 100;
DELETE FROM cajas WHERE Almacen IN (SELECT Codigo FROM ALMACENES WHERE Capacidad < (SELECT COUNT(*) FROM CAJAS WHERE Almacen = Codigo ));