SELECT Nombre FROM articulos;
SELECT Nombre, Precio FROM articulos;
SELECT Nombre, Precio FROM articulos WHERE Precio <= 200;
SELECT * FROM articulos WHERE Precio BETWEEN 60 AND 120;
SELECT Nombre, Precio * 166.386 AS 'Precio en pesetas' FROM articulos;
SELECT AVG(Precio) FROM articulos;
SELECT AVG(Precio) FROM articulos WHERE Fabricante = 2;
SELECT COUNT(*) FROM articulos WHERE Precio >= 180;
SELECT Nombre, Precio FROM articulos WHERE Precio >= 180 ORDER BY Precio DESC, Nombre ASC;
SELECT * FROM articulos, fabricantes WHERE articulos.Fabricante = fabricantes.Codigo;
SELECT articulos.Nombre, Precio, fabricantes.Nombre FROM articulos, fabricantes WHERE articulos.Fabricante = fabricantes.Codigo;
SELECT AVG(Precio), Fabricante FROM articulos GROUP BY Fabricante;
SELECT AVG(Precio), fabricantes.Nombre FROM articulos, fabricantes WHERE articulos.Fabricante = fabricantes.Codigo GROUP BY fabricantes.Nombre;
SELECT AVG(Precio), fabricantes.Nombre FROM articulos, fabricantes WHERE articulos.Fabricante = fabricantes.Codigo GROUP BY fabricantes.Nombre HAVING AVG(Precio) >= 150;
SELECT Nombre, Precio FROM articulos WHERE Precio = (SELECT MIN(Precio) FROM articulos);
SELECT a.Nombre, a.Precio, f.Nombre FROM articulos a, fabricantes f WHERE a.Fabricante = f.Codigo AND a.Precio = (SELECT MAX(a.Precio) FROM articulos a WHERE a.Fabricante = f.Codigo);
INSERT INTO articulos (Codigo, Nombre, Precio ,Fabricante) VALUES (11, 'Altavoces', 70, 2);
UPDATE ARTICULOS SET Nombre = 'Impresora Laser' WHERE Codigo = 8;
UPDATE ARTICULOS SET Precio = Precio * 0.9;
UPDATE ARTICULOS SET Precio = Precio - 10 WHERE Precio >= 120;